
package com.example.demo.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.demo.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://service.demo.example.com/", className = "com.example.demo.service.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.demo.example.com/", className = "com.example.demo.service.SaveResponse")
    @Action(input = "http://service.demo.example.com/ProductService/saveRequest", output = "http://service.demo.example.com/ProductService/saveResponse")
    public boolean save(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.demo.service.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDetail", targetNamespace = "http://service.demo.example.com/", className = "com.example.demo.service.GetDetail")
    @ResponseWrapper(localName = "getDetailResponse", targetNamespace = "http://service.demo.example.com/", className = "com.example.demo.service.GetDetailResponse")
    @Action(input = "http://service.demo.example.com/ProductService/getDetailRequest", output = "http://service.demo.example.com/ProductService/getDetailResponse")
    public Product getDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.example.demo.service.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://service.demo.example.com/", className = "com.example.demo.service.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://service.demo.example.com/", className = "com.example.demo.service.GetListResponse")
    @Action(input = "http://service.demo.example.com/ProductService/getListRequest", output = "http://service.demo.example.com/ProductService/getListResponse")
    public List<Product> getList();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.example.demo.service.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sellProduct", targetNamespace = "http://service.demo.example.com/", className = "com.example.demo.service.SellProduct")
    @ResponseWrapper(localName = "sellProductResponse", targetNamespace = "http://service.demo.example.com/", className = "com.example.demo.service.SellProductResponse")
    @Action(input = "http://service.demo.example.com/ProductService/sellProductRequest", output = "http://service.demo.example.com/ProductService/sellProductResponse")
    public Product sellProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
